// @ts-ignore
import Centria from './assets/pictures/centria.png';
// @ts-ignore
import Ksl from './assets/pictures/ksl.png';
// @ts-ignore
import Hakalahti from './assets/pictures/hakalahti.png';

const skillsList = [
    { title: 'JavaScript', value: 0.85 },
    { title: 'TypeScript', value: 0.85 },
    { title: 'Fullstack', value: 0.85 },
    { title: 'React', value: 0.75 },
    { title: 'React Native', value: 0.75 },
    { title: 'UI/UX', value: 0.75 },
    { title: 'Express JS ', value: 0.75 },
    { title: 'Node JS ', value: 0.60 },
    { title: 'Python', value: 0.70 },
    { title: 'Java', value: 0.5 },
    { title: 'Kotlin', value: 0.5 },
    { title: 'GraphQL', value: 0.5 },
    { title: 'MUI', value: 0.80 },
    { title: 'C#', value: 0.50 },
    { title: 'C++', value: 0.50 },
    { title: 'SQL', value: 0.80 },
    { title: 'Linux', value: 1 },
    { title: 'Redux ', value: 0.70},
    { title: 'MongoDB ', value: 0.70 },
    { title: 'Cypress & Jest ', value: 0.70 },
    { title: 'CI/CD', value: 0.70 },
    { title: 'CCNA', value: 0.60 },
]

const education = [
    {
        id: 0,
        school: 'Centria University of Applied Sciences',
        schoolLogo: Centria,
        links: {
            website: 'https://net.centria.fi/',
            facebook: 'https://www.facebook.com/centriaamk/',
            instagram: 'https://www.instagram.com/centriaamk/',
            x: 'https://x.com/centriaamk',
        },
        courses: [
            {
                courseName: 'FullStackOpen',
                courseLink: 'https://fullstackopen.com',
                schoolLink: 'https://www.helsinki.fi/fi',
                schoolName: 'University of Helsinki',
                dateFinished: '19.9.2022',
                grade: 4,
            },
            {
                courseName: 'Tietokannat (SQL)',
                courseLink: 'https://centria.github.io/tietokannat/',
                schoolLink: 'https://net.centria.fi/',
                schoolName: 'Centria UAS',
                dateFinished: '4.3.2024',
                grade: 5,
            },
            {
                courseName: 'Ohjelmistoprojeki',
                courseLink: '',
                schoolLink: 'https://net.centria.fi/',
                schoolName: 'Centria UAS',
                dateFinished: '25.1.2024',
                grade: 4,
            },
            {
                courseName: 'Käyttöliittymien suunnittelu ja kehittäminen',
                courseLink: '',
                schoolLink: 'https://net.centria.fi/',
                schoolName: 'Centria UAS',
                dateFinished: '14.12.2023',
                grade: 4,
            },
            {
                courseName: 'Relaatiotietokannat ja SQL',
                courseLink: '',
                schoolLink: 'https://net.centria.fi/',
                schoolName: 'Centria UAS',
                dateFinished: '4.3.2024',
                grade: 5,
            },
            {
                courseName: 'Linux essentials',
                courseLink: '',
                schoolLink: 'https://net.centria.fi/',
                schoolName: 'Centria UAS',
                dateFinished: '27.4.2022',
                grade: 3,
            },
            {
                courseName: 'Sulautetut järjestelmät',
                courseLink: '',
                schoolLink: 'https://net.centria.fi/',
                schoolName: 'Centria UAS',
                dateFinished: '20.12.2023',
                grade: 3,
            },
            {
                courseName: 'IP-verkot',
                courseLink: '',
                schoolLink: 'https://net.centria.fi/',
                schoolName: 'Centria UAS',
                dateFinished: '10.5.2021',
                grade: 4,
            },
            {
                courseName: 'Käyttöjärjestelmät',
                courseLink: '',
                schoolLink: 'https://net.centria.fi/',
                schoolName: 'Centria UAS',
                dateFinished: '14.10.2022',
                grade: 4,
            },
            {
                courseName: 'IoT ja Big Data',
                courseLink: '',
                schoolLink: 'https://net.centria.fi/',
                schoolName: 'Centria UAS',
                dateFinished: '2.5.2024',
                grade: 2,
            },
            {
                courseName: 'Tietotekniikka',
                courseLink: '',
                schoolLink: 'https://net.centria.fi/',
                schoolName: 'Centria UAS',
                dateFinished: '2.3.2021',
                grade: 3,
            },
            {
                courseName: 'Ohjelmoinnin perusteet',
                courseLink: '',
                schoolLink: 'https://net.centria.fi/',
                schoolName: 'Centria UAS',
                dateFinished: '9.3.2021',
                grade: 5,
            },
            {
                courseName: 'C-kieli',
                courseLink: '',
                schoolLink: 'https://net.centria.fi/',
                schoolName: 'Centria UAS',
                dateFinished: '12.5.2021',
                grade: 5,
            },
            {
                courseName: 'Algoritmit ja tietorakenteet',
                courseLink: '',
                schoolLink: 'https://net.centria.fi/',
                schoolName: 'Centria UAS',
                dateFinished: '13.12.2022',
                grade: 3,
            },
            {
                courseName: 'Palvelinohjelmointi',
                courseLink: '',
                schoolLink: 'https://net.centria.fi/',
                schoolName: 'Centria UAS',
                dateFinished: '24.4.2023',
                grade: 4,
            },
            {
                courseName: 'Ohjelmistotekniikka',
                courseLink: '',
                schoolLink: 'https://net.centria.fi/',
                schoolName: 'Centria UAS',
                dateFinished: '27.4.2023',
                grade: 2,
            },
            {
                courseName: 'Olio-ohjelmointi',
                courseLink: '',
                schoolLink: 'https://net.centria.fi/',
                schoolName: 'Centria UAS',
                dateFinished: '12.12.2022',
                grade: 3,
            },
            {
                courseName: 'CCNA R&S: Introduction to Networks',
                courseLink: '',
                schoolLink: 'https://net.centria.fi/',
                schoolName: 'Centria UAS',
                dateFinished: '13.4.2022',
                grade: 3,
            },
            {
                courseName: 'CCNA R&S: Routing and Switching Essentials',
                courseLink: '',
                schoolLink: 'https://net.centria.fi/',
                schoolName: 'Centria UAS',
                dateFinished: '13.12.2022',
                grade: 1,
            },
            {
                courseName: 'CCNA: Security',
                courseLink: '',
                schoolLink: 'https://net.centria.fi/',
                schoolName: 'Centria UAS',
                dateFinished: '14.12.2023',
                grade: 1,
            },
            {
                courseName: 'Mobiiliverkot',
                courseLink: '',
                schoolLink: 'https://net.centria.fi/',
                schoolName: 'Centria UAS',
                dateFinished: '22.5.2024',
                grade: 2,
            },
            {
                courseName: 'Algebra',
                courseLink: '',
                schoolLink: 'https://net.centria.fi/',
                schoolName: 'Centria UAS',
                dateFinished: '13.11.2020',
                grade: 4,
            },
            {
                courseName: 'Funktiot',
                courseLink: '',
                schoolLink: 'https://net.centria.fi/',
                schoolName: 'Centria UAS',
                dateFinished: '23.4.2021',
                grade: 5,
            },
            {
                courseName: 'Geometria',
                courseLink: '',
                schoolLink: 'https://net.centria.fi/',
                schoolName: 'Centria UAS',
                dateFinished: '10.2.2021',
                grade: 4,
            },
            {
                courseName: 'Differentiaalilaskenta',
                courseLink: '',
                schoolLink: 'https://net.centria.fi/',
                schoolName: 'Centria UAS',
                dateFinished: '27.11.2021',
                grade: 2,
            },
            {
                courseName: 'Integraalilaskenta',
                courseLink: '',
                schoolLink: 'https://net.centria.fi/',
                schoolName: 'Centria UAS',
                dateFinished: '30.3.2022',
                grade: 4,
            },
            {
                courseName: 'Tilastomatematiikka',
                courseLink: '',
                schoolLink: 'https://net.centria.fi/',
                schoolName: 'Centria UAS',
                dateFinished: '18.5.2022',
                grade: 2,
            },
            {
                courseName: 'Yrittäjyys',
                courseLink: '',
                schoolLink: 'https://net.centria.fi/',
                schoolName: 'Centria UAS',
                dateFinished: '29.5.2024',
                grade: 2,
            },
            {
                courseName: 'Digitaalitekniikka',
                courseLink: '',
                schoolLink: 'https://net.centria.fi/',
                schoolName: 'Centria UAS',
                dateFinished: '19.3.2024',
                grade: 3,
            },
            {
                courseName: 'Elektroniikan perusteet',
                courseLink: '',
                schoolLink: 'https://net.centria.fi/',
                schoolName: 'Centria UAS',
                dateFinished: '1.3.2021',
                grade: 3,
            },
            {
                courseName: 'Automaatiotekniikan perusteet',
                courseLink: '',
                schoolLink: 'https://net.centria.fi/',
                schoolName: 'Centria UAS',
                dateFinished: '11.5.2021',
                grade: 3,
            }
        ]
    },
    {
        id: 1,
        school: 'Kokkolan suomalainen lukio',
        schoolLogo: Ksl,
        links: {
            website: 'https://ksl2016.blogspot.com/',
            x : 'https://twitter.com/KokkolaKarleby',
        },
    },
    {
        id: 2,
        schoolLogo: Hakalahti,
        school: 'Hakalahden koulu',
        links: {
            website : 'https://hakalahdenkoulu.wordpress.com/',
            instagram : 'https://www.instagram.com/hakalahden_koulu/',
            x : 'https://twitter.com/KokkolaKarleby',
        },
    },
]

export { skillsList, education }